Update ChInfo, Notif to use uniform data formats
hyperledger-labs/perun-node pull request #115
Opened 2020-10-06 17:45 UTC by manoranjith

#### Description

    
- This is changeset 3 for using uniform data formats accross different
APIs.
    
 - Update ChInfo and then update ChProposalNotif, ChUpdateNotif,
ChCloseNotif to use previously defined BalInfo, ChInfo. As a result,
these notifs don't have any unprocessed data.

##### Category

Implementation Task

##### Relevant issue

Relates to #108.

#### Testing

No new functionality was added, update existing tests for change in data types. All existing tests should pass.

##### Steps to run the tests

#### Checklist 

- [x] Name is added to the NOTICE file, if it is not present already.
- [x] Changes are rebased onto the target branch.

2020-10-06 18:12 UTC, manoranjith commented
Should be merged only after #113.

2020-10-07 13:25 UTC, anagha-ks requested changes

2020-10-07 13:25 UTC, anagha-ks commented on session/channel.go
> +// makeApp returns perun.makeApp formed from the given add def and app data.
```suggestion
// makeApp returns perun.makeApp formed from the given app def and app data.
```

2020-10-07 13:39 UTC, anagha-ks approved these changes

2020-10-07 14:07 UTC, merged