Combine channel close notif into update notif
hyperledger-labs/perun-node pull request #117
Opened 2020-10-06 18:50 UTC by manoranjith

#### Description

- Previously, a separate subscription have to be made for receiving
channel close notifs (1 sub/session) and for receiving channel update
notifs (1 sub/ch). Now both are combined into channel update
subscription itself. To differentiate the context of notifications,
added a Type field to the notification message.

- Also, Settle and close a channel when a final update is accepted.

##### Category

Implementation Task

##### Relevant issue

Relates to #107. There is one more pull requests, where channels are removed from session once they are closed.
These two PRs together will close the issue.

#### Testing

All existing tests should pass, including the modified ones (as stated below).

##### Steps to run the tests

1. Remove tests relates to channel close subscription.
2. Updated `Test_Integ_Role` in `session` and  in `api/grpc` to use channel update subscriptions instead of channel close subscriptions to receive the 
3.  

#### Checklist 

- [x] Name is added to the NOTICE file, if it is not present already.
- [x] Changes are rebased onto the target branch.

2020-10-07 13:36 UTC, manoranjith commented
Channel Lifecycle after applying this change is described in the below diagram.
![image](https://user-images.githubusercontent.com/16356179/95338035-1e546800-08d0-11eb-9aa7-f078675bdccc.png)

2020-10-08 07:40 UTC, manoranjith commented
Rebased onto latest develop to resolve merge conflicts

2020-10-08 09:56 UTC, anagha-ks requested changes

2020-10-08 09:56 UTC, anagha-ks commented on api/grpc/server_integ_test.go
> +		// Bob closes payment channel, Alice receives notification for and rejects final update,
```suggestion
		// Bob closes payment channel, Alice receives notification for rejects and final update,
```

2020-10-08 11:43 UTC, anagha-ks approved these changes

2020-10-08 11:44 UTC, merged