Use new error type & structured log in AddPeerID
hyperledger-labs/perun-node pull request #148
Opened 2021-02-05 08:21 UTC by manoranjith

#### Description

  
For AddPeerID API:
  - Update it to return the newly defined error type. To identify specific
    error cases, added error constants in the "ID provider" package.
  
  - Log the request, error/success response are logged in
    a structured format (#133).

##### Category

Implementation Task

##### Relevant issue

Relates to #132, #133.

#### Testing

##### Steps to run the tests

1. Updated test `Test_YAML_Write_Read` in `idprovider/local` package for the newly added error constants.
2. Updated test `Test_Session_AddPeerID` in `session` package and `Test_Integ_New` in `node` package for using new error type in `AddPeerID` api.

#### Checklist 

- [x] Name is added to the NOTICE file, if it is not present already.
- [x] Changes are rebased onto the target branch.

2021-02-09 10:32 UTC, manoranjith commented
Rebased onto latest develop.

2021-02-10 04:23 UTC, anagha-ks requested changes

2021-02-10 04:23 UTC, anagha-ks commented on node/node.go
> +// newly defined APIErrorV2 format introduced for the purposing of refactoring.
```suggestion
// newly defined APIErrorV2 format introduced for the purpose of refactoring.
```

2021-02-10 04:23 UTC, anagha-ks commented on errorsV2.go
> +// APIError represents the error that will returned by the API of perun node.
```suggestion
// APIError represents the error that will be returned by the API of perun node.
```

2021-02-12 09:04 UTC, anagha-ks approved these changes

2021-02-12 09:44 UTC, merged