132 channel sub unsub update
hyperledger-labs/perun-node pull request #157
Opened 2021-02-23 04:19 UTC by anagha-ks

#### Description
For SubPayChUpdates, UnsubPayChUpdates API:
- Update it to return the newly defined error type (#132).
- Log the request, error/success response are logged in a structured
format (#133).

##### Category

Implementation Task

##### Relevant issue
Relates to #132, #133

#### Testing

1. Updated `Test_SubPayChUpdates` & `Test_UnsubPayChUpdates` in `payment` package
2. Updated `Test_SubUnsubChUpdate` in `session` package

##### Steps to run the tests

1.All existing tests should pass
2.
3.  

#### Checklist 

- [x] Name is added to the NOTICE file, if it is not present already.
- [x] Changes are rebased onto the target branch.

2021-02-24 11:09 UTC, anagha-ks commented
Rebased onto current develop.

2021-02-25 10:19 UTC, manoranjith commented on session/channel.go
>  	ch.Debug("Received request: channel.SubChUpdates")
Can you also update the log message to include the method name as a field. You can use your previous PR  (#153) as reference.

2021-02-25 10:23 UTC, manoranjith commented on session/channel.go
> +		ch.Error(apiErr)
```suggestion
```
The error is already logged in the previous line.

2021-02-25 10:24 UTC, manoranjith commented on session/channel.go
>  	ch.Debug("Received request: channel.UnsubChUpdates")
Update the log message. See the above [comment](https://github.com/hyperledger-labs/perun-node/pull/157/files#r582712783).

2021-02-25 10:37 UTC, manoranjith requested changes

2021-02-25 10:37 UTC, manoranjith commented on session/channel.go
> +		apiErr := perun.NewAPIErrV2ResourceNotFound("unsubscription to channel updates", ch.ID(), ErrNoActiveSub.Error())
```suggestion
		apiErr := perun.NewAPIErrV2ResourceNotFound("subscription to channel updates", ch.ID(), ErrNoActiveSub.Error())
```

It is `subscription to channel updates` that is not found.

2021-02-25 10:37 UTC, manoranjith commented on session/channel_test.go
> +	assert.Equal(t, "unsubscription to channel updates", addInfo1.Type)
```suggestion
	assert.Equal(t, "subscription to channel updates", addInfo1.Type)
```

2021-02-25 10:37 UTC, manoranjith commented on session/channel_test.go
> +	assert.Equal(t, "unsubscription to channel updates", addInfo1.Type)
Could you also add assertions on the returned error for the sub tests `Sub_channelClosed` and `Unsub_channelClosed`.

2021-02-25 10:37 UTC, manoranjith commented on session/role_integ_test.go
> +		require.Equal(t, err, apiError)
Assert for the individual properties of the error as it has been done in other parts of this PR.

2021-02-25 10:37 UTC, manoranjith commented on session/session.go
> +
```suggestion
```

Unnecessary new line.

2021-02-25 12:23 UTC, manoranjith approved these changes

2021-02-25 12:25 UTC, merged