163 add tests for collaborative and  non-collaborative close
hyperledger-labs/perun-node pull request #164
Opened 2021-03-02 14:26 UTC by manoranjith

#### Description

Added test cases for both collaborative and non-collaborative close in integration tests.

##### Category

Implementation Task

##### Relevant issue

Closes #163.
#### Testing

The test cases are added to `Test_Integ_Role`. 

##### Steps to run the tests

1.  In one terminal:
```
ganache-cli -b 1 --account="0x1fedd636dbc7e8d41a0622a2040b86fea8842cef9d4aa4c582aad00465b7acff,100000000000000000000" --account="0xb0309c60b4622d3071fad3e16c2ce4d0b1e7758316c187754f4dd0cfb44ceb33,100000000000000000000"
```
2. In another terminal:
```
cd session && go test -cover -p 1 -count=1 -tags=integration -run Test_Integ_Role
```
  
#### Checklist 

- [x] Name is added to the NOTICE file, if it is not present already.
- [x] Changes are rebased onto the target branch.

2021-03-04 10:44 UTC, manoranjith commented
Rebasing to latest develop branch

2021-03-10 09:28 UTC, anagha-ks requested changes

2021-03-10 09:28 UTC, anagha-ks commented on session/role_integ_test.go
> +	// 2. The other channel will be user for non-collaborative close.
```suggestion
	// 2. The other channel will be used for non-collaborative close.
```

2021-03-12 10:18 UTC, manoranjith commented
I have accepted your changes, can you please review it again. @anagha-ks

2021-03-12 10:27 UTC, anagha-ks approved these changes

2021-03-12 10:30 UTC, merged